name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -  name: Checkout
       uses: actions/checkout@v3
    
    - name: Add SSH key
      run: |
                  mkdir -p /home/runner/.ssh
                  # you're SSH-ing into
                  ssh-keyscan ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
                  # DOKKU_SSH_KEY is the name of the repository secret
                  echo "${{ secrets.PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
                  chmod 400 /home/runner/.ssh/github_actions
                  ssh-agent -a /tmp/ssh_agent.sock > /dev/null	
                  ssh-add /home/runner/.ssh/github_actions
                  ls -l /home/runner/.ssh/github_actions

    - name: Set version number
      run: |
        echo "VERSION_NUMBER=$((GITHUB_RUN_NUMBER))" >> $GITHUB_ENV
        cat $GITHUB_ENV
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github-actions-role
        role-session-name: samplerolesession
        aws-region: eu-west-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: actions/setup-go@v4
      with:
          go-version: '1.20'
          cache: false
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.53

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "kamma/whoami:${{ env.VERSION_NUMBER }}"
    
    - name: Scan for vulnerabilities
      id: scan
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: "kamma/whoami:${{ env.VERSION_NUMBER }}"
        dockerfile: ./Dockerfile
        severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

    - name: JSON result
      run: cat ${{ steps.scan.outputs.json }} 

    # when tests runs successfully will build final image and push to ECR 
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: kamma-ecr-repo
        IMAGE_TAG: "kamma-whoami-${{ env.VERSION_NUMBER }}"
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


